### ISSUE TITLE
Unknown plugin "uglify:after"

### ISSUE THREAD

**Issue by rochapablo** [RReverser/babel-plugin-uglify#7] opened 2016-05-04 13:45 UTC
```
$ npm install babel-plugin-uglify --save
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
```

**package.json**

```
"scripts": {
    "build": "babel src -d lib && babel public/assets/js/script.js",
  },
  "babel": {
    "plugins": ["uglify:after"]
  }
```

```
events.js:154
      throw er; // Unhandled 'error' event
      ^
ReferenceError: Unknown plugin "uglify:after" specified in "D:\\www\\noonii\\usuario\\package.json" at 0, attempted to resolve relative to "D:\\www\\noonii\\usuario"
    at D:\www\noonii\usuario\node_modules\gulp-babel\node_modules\babel-core\lib\transformation\file\options\option-manager.js:179:17
    at Array.map (native)
    at Function.normalisePlugins (D:\www\noonii\usuario\node_modules\gulp-babel\node_modules\babel-core\lib\transformation\file\options\option-manager.js:155:20)
    at OptionManager.mergeOptions (D:\www\noonii\usuario\node_modules\gulp-babel\node_modules\babel-core\lib\transformation\file\options\option-manager.js:277:36)
    at OptionManager.addConfig (D:\www\noonii\usuario\node_modules\gulp-babel\node_modules\babel-core\lib\transformation\file\options\option-manager.js:207:10)
    at OptionManager.findConfigs (D:\www\noonii\usuario\node_modules\gulp-babel\node_modules\babel-core\lib\transformation\file\options\option-manager.js:419:30)
    at OptionManager.init (D:\www\noonii\usuario\node_modules\gulp-babel\node_modules\babel-core\lib\transformation\file\options\option-manager.js:461:12)
    at File.initOptions (D:\www\noonii\usuario\node_modules\gulp-babel\node_modules\babel-core\lib\transformation\file\index.js:194:75)
    at new File (D:\www\noonii\usuario\node_modules\gulp-babel\node_modules\babel-core\lib\transformation\file\index.js:123:22)
    at Pipeline.transform (D:\www\noonii\usuario\node_modules\gulp-babel\node_modules\babel-core\lib\transformation\pipeline.js:45:16)
```

What am I missing here?

**Comment by RReverser** [comment] 2016-05-04 14:05
I suppose duplicate of #3?

**Closed as completed** 2016-05-04 15:36 UTC
